### ISSUE TITLE
Please use the docker hub image in the quickstart

### ISSUE THREAD

**Issue by paulvancoller-adeptadvisory** [GrindrodBank/dokuti#19]
**Is your feature request related to a problem? Please describe.**
When running the quickstart it does a local build.

**Describe the solution you'd like**
That the quickstart pull the docker hub image.

**Describe alternatives you've considered**
no alternatives considered.

**Comment by VictorSzewczenko** [comment]
Hi Paul. 

This is an excellent recommendation and will be included within the next release of Dokuti.

Thanks for your feedback.

**Comment by gm7** [comment]
This has been completed, the image `grindrodbank/dokuti:latest` is pulled from docker hub.
