### ISSUE TITLE
Add axios client generation to CircleCI pipeline

### ISSUE THREAD

**Issue by philipstaffordwood** [GrindrodBank/dokuti#40]
**Is your feature request related to a problem? Please describe.**
No. A new feature.

**Describe the solution you'd like**
An official [Axios client](https://github.com/axios/axios) autogenerated from the project [openapi specification](https://github.com/GrindrodBank/dokuti/blob/master/doc/dokuti_api.yml) would be beneficial for front-end developers.

**Comment by gm7** [comment]
This has been completed and the Axios client library is available here:
https://www.npmjs.com/package/@grindrodbank/dokuti-api
