### ISSUE TITLE
Ability to link attributes to a version the document, not just the latest version

### ISSUE THREAD

**Issue by melissapalmer** [GrindrodBank/dokuti#60]
**Is your feature request related to a problem? Please describe.**
Currently you cannot have the same attribute with different values for different versions of a document. For example: something like expiry date can be kept with specific version of document like a passport. Having it only on latest is not sufficient if you wanting to know the expiry date of each version in its own right. You might upload the 2nd passport before expiry of 1st. 

**Describe the solution you'd like**
Ability to associated attributes of a document with versions and not just the latest version of the document. 

**Describe alternatives you've considered**
Not using the attribute functionality of Dokuti, instead keeping attributes for documents elsewhere.

**Comment by akorneyc** [comment]
After uploading new version of the document should attributes inherits from prev doc versions?

**Comment by melissapalmer** [comment]
Done in PR #68
